//  Count the Number of Vowels in a String

#include<bits/stdc++.h>
using namespace std;
int main(){
    string input;
    cout << "Enter the string " << endl;
    get
    // ch is character 
    int vowel_Count = 0;
    for(char ch : input){
        if ( ch == 'a' | ch == 'e' | ch == 'i' | ch == 'o' | ch == 'u' |
             ch == 'A' | ch == 'E' | ch == 'I' | ch == 'O' | ch == 'U')
    vowel_Count++;
    }

    cout<< "Number of Vowels is "<<vowel_Count<<endl;
}